id: P001846
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG14732
  title: སྡེ་དགེ་པར་ཁང་གི་པར་ཤིང་དཀར་ཆག་བོད་རྒྱ་ཤན་སྦྱར།
  author: ''
  volumes:
    bd7d1708a112457d8b1e3523a5f203cc:
      image_group_id: I1KG14765
      title: ''
      volume_number: 1
      total_pages: 476
      base_file: v001.txt
